version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mytapp_password
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
